FROM ubuntu:latest
# We base this on ubuntu

# Certbot for static content nginx

# Set env. replace right most column with values specific to your environment
ARG NGINX_DOMAIN
ENV NGINX_DOMAIN ${NGINX_DOMAIN:-example.com}
ARG NGINX_WWWDOMAIN
ENV NGINX_WWWDOMAIN ${NGINX_WWWDOMAIN:-www.example.com}

LABEL maintainer=dansta

# Check ourselves to know we are alive
HEALTHCHECK --interval=15s --timeout=3s CMD  certbot renew --dry-run || exit 1

# Update and install packages
RUN apt-get update && \
    apt-get install -y \
                       software-properties-common \
                       cron && \
    add-apt-repository -y ppa:certbot/certbot && \
    apt-get update && \
    apt-get -y install python3-certbot-nginx && \
    rm -rf /var/lib/apt/lists/*

# Add renewalscripts
ADD files/crontab /etc/cron.d/certbot_renew
RUN chmod 0644 /etc/cron.d/certbot_renew
RUN touch /var/log/cron.log

# Remove what we do not need for runtime
RUN apt-get -y autoremove

# Add remote log directory volume and a directory from which we grab the web content
VOLUME /var/log/
VOLUME /etc/nginx/
VOLUME /usr/share/nginx/html/

# Run this per default
CMD ["/usr/bin/certbot", "--nginx", "certonly", "--cert-name", "${NGINX_DOMAIN}"]
